codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "80...100"

  project:
    default:
      threshold: 1%
  patch:
    default:
      threshold: 1%

comment: off
