env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
globals:
  React: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - varsIgnorePattern: ".Component"
  no-console:
    - off
  react/display-name: 1
  react/forbid-prop-types: 0
  react/jsx-sort-props: 1
  react/sort-comp: 1
