exclude:
  - './app/front/stylesheets/open-iconic-bootstrap.scss'
  - './app/front/stylesheets/exclude-scss-lint.scss'
  - './app/front/stylesheets/react-datepicker.css'
  - './app/front/stylesheets/autosuggest.scss'
  - './app/front/stylesheets/react-tooltip.scss'
linters:
  SingleLinePerSelector:
    enabled: false
  EmptyRule:
    enabled: false
