exclude:
  - './app/assets/stylesheets/open-iconic-bootstrap.scss'
  - './app/assets/stylesheets/react-datepicker.css'
  - './app/assets/stylesheets/autosuggest.scss'
  - './app/assets/stylesheets/react-tooltip.scss'
linters:
  SingleLinePerSelector:
    enabled: false
  EmptyRule:
    enabled: false
