version: '3'

services:
  db:
    container_name: pig-book_postgres
    build: ./docker
    ports:
      - 5433:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  redis:
    container_name: pig-book_redis
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgresql:
    driver: local
  redis:
    driver: local
