version: '3'

services:
  redis:
    container_name: pig-book_redis
    hostname: redis
    image: redis:6.0.5
    ports:
      - 6377:6379
    volumes:
      - redis:/var/lib/redis/data

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'

volumes:
  redis:
    driver: local
