version: '3'

services:
  db:
    container_name: pig-book_postgres
    build: ./docker
    ports:
      - 5433:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  redis:
    container_name: pig-book_redis
    image: redis:4.0.14
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  client:
    container_name: pig-book_react
    build: ./client
    command: "npm run start"
    volumes:
      - ./client:/myapp/client
    ports:
      - "${CLIENT_PORT}:3000"

volumes:
  postgresql:
    driver: local
  redis:
    driver: local
