server: &server
  working_directory: ~/pig-book
  docker:
    - image: circleci/ruby:2.7.3-node-browsers
      environment:
        RAILS_ENV: test
        NODE_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/pig_book_test
        DB_PASS: password
        DB_USER: postgres
        DB_HOST: localhost
        REDIS_HOST: redis
        TZ: Asia/Tokyo
        HOST_NAME: 127.0.0.1
        PORT: 33333
        SLACK_WEBHOOK_URL: ""
    - image: postgres:10.4-alpine
      environment:
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: pig_book_test
    - image: redis:4.0.9-alpine
  steps:
    - checkout

    - type: cache-restore
      key: pig_book-{{ checksum "Gemfile.lock" }}

    - run:
        name: Update bundler
        command: gem update bundler

    - run:
        name: Bundle install
        command: bundle install

    - type: cache-save
      key: pig_book-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

    - run:
        name: Create Database
        command: bundle exec rake db:create
    - run:
        name: Load Database Schema
        command: bundle exec rake db:schema:load

    - run:
        name: Ruby version
        command: ruby -v

    # Run rubocop
    - run:
        name: Run Rubocop
        command: bundle exec rubocop

    # Run rspec in parallel
    - run:
        name: Run yarn install
        command: yarn install

    - run:
        name: Compile webpack
        command: rails webpacker:compile

    - type: shell
      command: |
        bundle exec rspec \
          --format RspecJunitFormatter \
          --out /tmp/test-results/rspec.xml \
          --format progress \
          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

    # Save artifacts
    - store_artifacts:
        path: ./tmp/capybara
        destination: capybara-screenshot

    - store_artifacts:
        path: ./doc
        destination: autodoc

client: &client
  working_directory: ~/pig-book
  docker:
    - image: circleci/ruby:2.7.3-node-browsers
      environment:
        NODE_ENV: test
        TZ: Asia/Tokyo
        WDS_SOCKET_HOST: localhost
        SERVER_PORT: 3020
  steps:
    - checkout

    - run:
        name: Run yarn install
        working_directory: client
        command: yarn install

    - run:
        name: Run sass-lint
        working_directory: client
        command: yarn run sass-lint

    - run:
        name: Run ESLint
        working_directory: client
        command: yarn run eslint

version: 2
jobs:
  build_on_server:
    <<: *server
  build_on_client:
    <<: *client

workflows:
  version: 2
  main:
    jobs:
      - build_on_server
      - build_on_client
