AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - config.ru
    - Rakefile
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

# ABCサイズをMAX20に緩和
Metrics/AbcSize:
  Enabled: true
  Max: 20

# ModuleとClassの形式を選択可とする
Style/ClassAndModuleChildren:
  Enabled: false

# モジュールの行数制限についてテストファイルを除外
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/rails_helper.rb"
    - "spec/factories/*.rb"
