export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USER_STATUS_REQUEST = 'GET_USER_STATUS_REQUEST';
export const GET_USER_STATUS_SUCCESS = 'GET_USER_STATUS_SUCCESS';
export const GET_USER_STATUS_FAILURE = 'GET_USER_STATUS_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const CHANGE_PROFILE_LOCALE = 'CHANGE_PROFILE_LOCALE';
export const CHANGE_PROFILE_CURRENCY = 'CHANGE_PROFILE_CURRENCY';
export const SET_EDITING = 'SET_EDITING';
export const SET_EDITING_MEMO = 'SET_EDITING_MEMO';

export const PATCH_PROFILE_REQUEST = 'PATCH_PROFILE_REQUEST';
export const PATCH_PROFILE_SUCCESS = 'PATCH_PROFILE_SUCCESS';
export const PATCH_PROFILE_FAILURE = 'PATCH_PROFILE_FAILURE';

export const POST_CATEGORY_REQUEST = 'PATCH_CATEGORY_REQUEST';
export const POST_CATEGORY_SUCCESS = 'PATCH_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAILURE = 'PATCH_CATEGORY_FAILURE';

export const CHANGE_CATEGORY_BALANCE_OF_PAYMENTS = 'CHANGE_CATEGORY_BALANCE_OF_PAYMENTS';
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';

