export const GET_COOKIES_FAILURE = 'GET_COOKIES_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_USER_STATUS_REQUEST = 'GET_USER_STATUS_REQUEST'
export const GET_USER_STATUS_SUCCESS = 'GET_USER_STATUS_SUCCESS'
export const GET_USER_STATUS_FAILURE = 'GET_USER_STATUS_FAILURE'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const CHANGE_PROFILE_LOCALE = 'CHANGE_PROFILE_LOCALE'
export const CHANGE_PROFILE_CURRENCY = 'CHANGE_PROFILE_CURRENCY'
export const SET_EDITING = 'SET_EDITING'
export const SET_EDITING_MEMO = 'SET_EDITING_MEMO'

export const PATCH_PROFILE_REQUEST = 'PATCH_PROFILE_REQUEST'
export const PATCH_PROFILE_SUCCESS = 'PATCH_PROFILE_SUCCESS'
export const PATCH_PROFILE_FAILURE = 'PATCH_PROFILE_FAILURE'

export const POST_CATEGORY_REQUEST = 'POST_CATEGORY_REQUEST'
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS'
export const POST_CATEGORY_FAILURE = 'POST_CATEGORY_FAILURE'

export const CHANGE_CATEGORY_BALANCE_OF_PAYMENTS = 'CHANGE_CATEGORY_BALANCE_OF_PAYMENTS'
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME'

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const PATCH_CATEGORY_REQUEST = 'PATCH_CATEGORY_REQUEST'
export const PATCH_CATEGORY_SUCCESS = 'PATCH_CATEGORY_SUCCESS'
export const PATCH_CATEGORY_FAILURE = 'PATCH_CATEGORY_FAILURE'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE'

export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EXIT_CATEGORY = 'EXIT_CATEGORY'
export const EDIT_BREAKDOWN = 'EDIT_BREAKDOWN'
export const EXIT_BREAKDOWN = 'EXIT_BREAKDOWN'
export const EDIT_PLACE = 'EDIT_PLACE'
export const EXIT_PLACE = 'EXIT_PLACE'

export const GET_BREAKDOWNS_REQUEST = 'GET_BREAKDOWNS_REQUEST'
export const GET_BREAKDOWNS_SUCCESS = 'GET_BREAKDOWNS_SUCCESS'
export const GET_BREAKDOWNS_FAILURE = 'GET_BREAKDOWNS_FAILURE'

export const POST_BREAKDOWN_REQUEST = 'POST_BREAKDOWN_REQUEST'
export const POST_BREAKDOWN_SUCCESS = 'POST_BREAKDOWN_SUCCESS'
export const POST_BREAKDOWN_FAILURE = 'POST_BREAKDOWN_FAILURE'

export const PATCH_BREAKDOWN_REQUEST = 'PATCH_BREAKDOWN_REQUEST'
export const PATCH_BREAKDOWN_SUCCESS = 'PATCH_BREAKDOWN_SUCCESS'
export const PATCH_BREAKDOWN_FAILURE = 'PATCH_BREAKDOWN_FAILURE'

export const POST_PLACE_REQUEST = 'POST_PLACE_REQUEST'
export const POST_PLACE_SUCCESS = 'POST_PLACE_SUCCESS'
export const POST_PLACE_FAILURE = 'POST_PLACE_FAILURE'

export const CHANGE_BREAKDOWN_NAME = 'CHANGE_BREAKDOWN_NAME'
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const DELETE_BREAKDOWN_REQUEST = 'DELETE_BREAKDOWN_REQUEST'
export const DELETE_BREAKDOWN_SUCCESS = 'DELETE_BREAKDOWN_SUCCESS'
export const DELETE_BREAKDOWN_FAILURE = 'DELETE_BREAKDOWN_FAILURE'

export const CHANGE_PLACE_NAME = 'CHANGE_PLACE_NAME'

export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE'

export const DELETE_PLACE_REQUEST = 'DELETE_PLACE_REQUEST'
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS'
export const DELETE_PLACE_FAILURE = 'DELETE_PLACE_FAILURE'

export const PATCH_PLACE_REQUEST = 'PATCH_PLACE_REQUEST'
export const PATCH_PLACE_SUCCESS = 'PATCH_PLACE_SUCCESS'
export const PATCH_PLACE_FAILURE = 'PATCH_PLACE_FAILURE'

export const GET_PLACE_CATEGORIES_REQUEST = 'GET_PLACE_CATEGORIES_REQUEST'
export const GET_PLACE_CATEGORIES_SUCCESS = 'GET_PLACE_CATEGORIES_SUCCESS'
export const GET_PLACE_CATEGORIES_FAILURE = 'GET_PLACE_CATEGORIES_FAILURE'

export const POST_PLACE_CATEGORIES_REQUEST = 'POST_PLACE_CATEGORIES_REQUEST'
export const POST_PLACE_CATEGORIES_SUCCESS = 'POST_PLACE_CATEGORIES_SUCCESS'
export const POST_PLACE_CATEGORIES_FAILURE = 'POST_PLACE_CATEGORIES_FAILURE'

export const POST_RECORD_REQUEST = 'POST_RECORD_REQUEST'
export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS'
export const POST_RECORD_FAILURE = 'POST_RECORD_FAILURE'

export const CHANGE_RECORD_PUBLISHED_ON = 'CHANGE_RECORD_PUBLISHED_ON'
export const CHANGE_RECORD_BALANCE_OF_PAYMENTS = 'CHANGE_RECORD_BALANCE_OF_PAYMENTS'
export const CHANGE_RECORD_CATEGORY = 'CHANGE_RECORD_CATEGORY'
export const CHANGE_RECORD_BREAKDOWN = 'CHANGE_RECORD_BREAKDOWN'
export const CHANGE_RECORD_PLACE = 'CHANGE_RECORD_PLACE'
export const CHANGE_RECORD_CHARGE = 'CHANGE_RECORD_CHARGE'
export const CHANGE_RECORD_CASHLESS_CHARGE = 'CHANGE_RECORD_CASHLESS_CHARGE'
export const CHANGE_RECORD_POINT = 'CHANGE_RECORD_POINT'
export const CHANGE_RECORD_MEMO = 'CHANGE_RECORD_MEMO'

export const COPY_RECORD = 'COPY_RECORD'

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST'
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS'
export const GET_RECORDS_FAILURE = 'GET_RECORDS_FAILURE'

export const PATCH_RECORD_REQUEST = 'PATCH_RECORD_REQUEST'
export const PATCH_RECORD_SUCCESS = 'PATCH_RECORD_SUCCESS'
export const PATCH_RECORD_FAILURE = 'PATCH_RECORD_FAILURE'

export const CHANGE_EDIT_RECORD_PUBLISHED_ON = 'CHANGE_EDIT_RECORD_PUBLISHED_ON'
export const CHANGE_EDIT_RECORD_BALANCE_OF_PAYMENTS = 'CHANGE_EDIT_RECORD_BALANCE_OF_PAYMENTS'
export const CHANGE_EDIT_RECORD_CATEGORY = 'CHANGE_EDIT_RECORD_CATEGORY'
export const CHANGE_EDIT_RECORD_BREAKDOWN = 'CHANGE_EDIT_RECORD_BREAKDOWN'
export const CHANGE_EDIT_RECORD_PLACE = 'CHANGE_EDIT_RECORD_PLACE'
export const CHANGE_EDIT_RECORD_CHARGE = 'CHANGE_EDIT_RECORD_CHARGE'
export const CHANGE_EDIT_RECORD_CASHLESS_CHARGE = 'CHANGE_EDIT_RECORD_CASHLESS_CHARGE'
export const CHANGE_EDIT_RECORD_POINT = 'CHANGE_EDIT_RECORD_POINT'
export const CHANGE_EDIT_RECORD_MEMO = 'CHANGE_EDIT_RECORD_MEMO'

export const EDIT_RECORD = 'EDIT_RECORD'
export const CLOSE_EDIT_MODAL = 'CLOSE_EDIT_MODAL'
export const CLEAR_EDITED_RECORD = 'CLEAR_EDITED_RECORD'
export const CLEAR_EDITED_CATEGORY = 'CLEAR_EDITED_CATEGORY'
export const CLEAR_EDITED_BREAKDOWN = 'CLEAR_EDITED_BREAKDOWN'
export const CLEAR_EDITED_PLACE = 'CLEAR_EDITED_PLACE'

export const GET_EDIT_RECORD_CATEGORY_REQUEST = 'GET_EDIT_RECORD_CATEGORY_REQUEST'
export const GET_EDIT_RECORD_CATEGORY_SUCCESS = 'GET_EDIT_RECORD_CATEGORY_SUCCESS'
export const GET_EDIT_RECORD_CATEGORY_FAILURE = 'GET_EDIT_RECORD_CATEGORY_FAILURE'

export const DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST'
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS'
export const DELETE_RECORD_FAILURE = 'DELETE_RECORD_FAILURE'

export const CLOSE_NEW_MODAL = 'CLOSE_NEW_MODAL'
export const SET_RECORD_SEARCH_PARAMS = 'SET_RECORD_SEARCH_PARAMS'
